# Generated by Django 6.0.4 on 2026-04-14 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_vpnclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpnclient',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vpn_client', to=settings.AUTH_USER_MODEL),
        ),
    ]
