# Generated by Django 6.0.4 on 2026-08-12 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0004_usernetwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupRegistrationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open_for_registration', models.BooleanField(default=True, verbose_name='Доступна при регистрации')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration_settings', to='auth.group')),
            ],
            options={
                'verbose_name': 'Настройка группы (регистрация)',
                'verbose_name_plural': 'Настройки групп (регистрация)',
            },
        ),
    ]
