# Generated by Django 6.0.4 on 2026-04-13 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0002_remove_task_proxmox_node_flag_hint_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVMInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxmox_vm_id', models.IntegerField(blank=True, null=True, verbose_name='ID VM в Proxmox')),
                ('ip_address', models.GenericIPAddressField(protocol='ipv4', unique=True, verbose_name='IP-адрес')),
                ('status', models.CharField(choices=[('running', 'Запущена'), ('stopped', 'Остановлена'), ('destroyed', 'Уничтожена')], default='stopped', max_length=20, verbose_name='Статус')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Время запуска')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task', verbose_name='Задание')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запущенная VM пользователя',
                'verbose_name_plural': 'Запущенные VM пользователей',
                'unique_together': {('user', 'task')},
            },
        ),
    ]
