# Generated by Django 6.0.4 on 2026-04-21 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_flag_flag_value'),
        ('vms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VMFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_flag', models.CharField(max_length=255, verbose_name='Сгенерированный флаг')),
                ('file_path', models.CharField(max_length=300, verbose_name='Путь, куда вставлен флаг')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flag_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.flag')),
                ('vm_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='vms.uservminstance')),
            ],
            options={
                'verbose_name': 'Флаг в VM',
                'verbose_name_plural': 'Флаги в VM',
                'unique_together': {('vm_instance', 'flag_obj')},
            },
        ),
    ]
