# Generated by Django 6.0.4 on 2026-04-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0002_vmflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservminstance',
            name='generated_flags',
            field=models.JSONField(blank=True, default=dict, verbose_name='Сгенерированные флаги (flag_id: generated_flag)'),
        ),
        migrations.DeleteModel(
            name='VMFlag',
        ),
    ]
