# Generated by Django 6.0.4 on 2026-04-13 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_value', models.CharField(max_length=255, verbose_name='Флаг')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание флага (для админа)')),
            ],
            options={
                'verbose_name': 'Флаг',
                'verbose_name_plural': 'Флаги',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название задания')),
                ('description', models.TextField(verbose_name='Описание')),
                ('task_type', models.CharField(choices=[('file', 'Файл на взлом'), ('vm', 'Виртуальная машина')], default='file', max_length=10, verbose_name='Тип задания')),
                ('file', models.FileField(blank=True, null=True, upload_to='tasks/files/', verbose_name='Файл для скачивания')),
                ('proxmox_template_id', models.IntegerField(blank=True, null=True, verbose_name='ID шаблона в Proxmox')),
                ('proxmox_node', models.CharField(blank=True, max_length=50, null=True, verbose_name='Нода Proxmox')),
                ('points', models.PositiveIntegerField(default=100, verbose_name='Баллы')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_flag', models.CharField(max_length=255, verbose_name='Отправленный флаг')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильно')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('flag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.flag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Сабмит',
                'verbose_name_plural': 'Сабмиты',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddField(
            model_name='flag',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='tasks.task'),
        ),
    ]
