# Generated by Django 6.0.4 on 2026-04-13 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='proxmox_node',
        ),
        migrations.AddField(
            model_name='flag',
            name='hint',
            field=models.CharField(blank=True, max_length=300, verbose_name='Подсказка (где искать флаг)'),
        ),
        migrations.AlterField(
            model_name='flag',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Описание для админа'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='flag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.flag'),
        ),
    ]
