# Generated by Django 6.0.4 on 2026-04-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_submission_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='readme',
            field=models.TextField(blank=True, help_text='Полное описание задания с форматированием. Поддерживает Markdown, картинки, код и т.д.', null=True, verbose_name='README (Markdown)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, verbose_name='Краткое описание'),
        ),
    ]
