# Generated by Django 6.0.4 on 2026-04-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_readme_alter_task_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='readme',
        ),
        migrations.AddField(
            model_name='flag',
            name='file_path',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Путь к файлу в VM (для авто-вставки)'),
        ),
        migrations.AlterField(
            model_name='flag',
            name='flag_value',
            field=models.CharField(blank=True, max_length=255, verbose_name='Флаг (если пусто — генерируется автоматически)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
