# Generated by Django 6.0.4 on 2026-04-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_task_readme_flag_file_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='readme',
            field=models.TextField(blank=True, help_text='Полное описание задания с форматированием. Поддерживает Markdown, картинки, код и т.д.', null=True, verbose_name='README (Markdown)'),
        ),
        migrations.AlterField(
            model_name='flag',
            name='flag_value',
            field=models.CharField(max_length=255, verbose_name='Флаг'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, verbose_name='Краткое описание'),
        ),
    ]
