# Generated by Django 6.0.4 on 2026-04-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_readme_alter_flag_flag_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flag',
            name='flag_value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Флаг (оставь пустым — будет генерироваться автоматически)'),
        ),
    ]
