# Generated by Django 6.0.4 on 2026-04-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_flag_flag_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='readme_file',
            field=models.FileField(blank=True, help_text='Загрузите HTML или PDF файл с полным описанием задания', null=True, upload_to='tasks/readme/', verbose_name='README файл (HTML или PDF)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='readme',
            field=models.TextField(blank=True, help_text='Устарело. Используйте поле ниже для загрузки файла.', null=True, verbose_name='README (Markdown) — устарело'),
        ),
    ]
