# Generated by Django 6.0.4 on 2026-08-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_task_readme_file_alter_task_readme'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='label',
            field=models.CharField(blank=True, help_text='Показывается участнику над полем ввода этого флага', max_length=100, verbose_name='Название флага (например: root, user)'),
        ),
    ]
