# Generated by Django 6.0.4 on 2026-08-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tasks', '0009_flag_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, help_text='Если не выбрана ни одна группа — задание видно всем одобренным участникам', related_name='tasks', to='auth.group', verbose_name='Доступно только группам'),
        ),
    ]
